name: Build Maker Trance VST2 Windows

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build-vst2:
    runs-on: ubuntu-22.04

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Baixar DPF
        run: |
          git clone \
            --depth 1 \
            --recursive \
            https://github.com/DISTRHO/DPF.git \
            dpf

      - name: Validar gerador e arquivos
        run: python3 tools/validate_project.py

      - name: Compilar VST2 Windows x64
        uses: distrho/dpf-cmake-action@v1
        with:
          target: win64
          dpf_path: dpf
          release: false
