#pragma once

#define DISTRHO_PLUGIN_BRAND "Alza Produz"
#define DISTRHO_PLUGIN_NAME "Maker Trance by Alza Produz"
#define DISTRHO_PLUGIN_URI "urn:alza-produz:maker-trance-vst2"
#define DISTRHO_PLUGIN_CLAP_ID "com.alzaproduz.makertrance"
#define DISTRHO_PLUGIN_BRAND_ID Alza
#define DISTRHO_PLUGIN_UNIQUE_ID MTA2

#define DISTRHO_PLUGIN_NUM_INPUTS 0
#define DISTRHO_PLUGIN_NUM_OUTPUTS 2
#define DISTRHO_PLUGIN_IS_RT_SAFE 1
#define DISTRHO_PLUGIN_IS_SYNTH 1
#define DISTRHO_PLUGIN_HAS_UI 1
#define DISTRHO_PLUGIN_WANT_MIDI_INPUT 1
#define DISTRHO_PLUGIN_WANT_MIDI_OUTPUT 1
#define DISTRHO_PLUGIN_WANT_PROGRAMS 1
#define DISTRHO_PLUGIN_WANT_STATE 0
#define DISTRHO_PLUGIN_WANT_TIMEPOS 1
#define DISTRHO_PLUGIN_WANT_DIRECT_ACCESS 0

#define DISTRHO_UI_FILE_BROWSER 0
#define DISTRHO_UI_USER_RESIZABLE 0
#define DISTRHO_UI_DEFAULT_WIDTH 1000
#define DISTRHO_UI_DEFAULT_HEIGHT 620
